L4Re - L4 Runtime Environment: L4::Icu Class Reference
L4::Icu Class Reference
Interrupt controller
C++ version of an interrupt controller.
Data Structures
class Info
Info for an ICU.
Public Member Functions
l4_msgtag_t bind (unsigned irqnum, L4::Cap< Irq > irq, l4_utcb_t *utcb=l4_utcb()) throw ()
Bind an interrupt vector of an interrupt controller to an interrupt object.
l4_msgtag_t unbind (unsigned irqnum, L4::Cap< Irq > irq, l4_utcb_t *utcb=l4_utcb()) throw ()
Remove binding of an interrupt vector from the interrupt controller object.
l4_msgtag_t info (l4_icu_info_t *info, l4_utcb_t *utcb=l4_utcb()) throw ()
Get info about capabilites of ICU.
l4_msgtag_t msi_info (unsigned irqnum, l4_umword_t *msg, l4_utcb_t *utcb=l4_utcb()) throw ()
Get MSI info about IRQ.
l4_msgtag_t mask (unsigned irqnum, l4_umword_t *label=0, l4_timeout_t to=L4_IPC_NEVER, l4_utcb_t *utcb=l4_utcb()) throw ()
Mask an IRQ vector.
l4_msgtag_t unmask (unsigned irqnum, l4_umword_t *label=0, l4_timeout_t to=L4_IPC_NEVER, l4_utcb_t *utcb=l4_utcb()) throw ()
Unmask an IRQ vector.
l4_msgtag_t set_mode (unsigned irqnum, l4_umword_t mode, l4_utcb_t *utcb=l4_utcb()) throw ()
Set mode of interrupt.
Public Member Functions inherited from L4::Kobject
l4_msgtag_t dec_refcnt (l4_mword_t diff, l4_utcb_t *utcb=l4_utcb())
Decrement the in kernel reference counter for the object.
Additional Inherited Members
Protected Member Functions inherited from L4::Kobject
l4_cap_idx_t cap () const throw ()
Return capability selector.
Detailed Description
C++ version of an interrupt controller.
#include <l4/sys/icu>
See Also
Interrupt controller for an overview and C bindings.
Definition at line 125 of file irq.
Member Function Documentation
l4_msgtag_t L4::Icu::bind (unsigned irqnum, L4::Cap< Irq > irq, l4_utcb_t * utcb = l4_utcb()) throw () inline
Bind an interrupt vector of an interrupt controller to an interrupt object.
Parameters
icu ICU to use.
irqnum IRQ vector at the ICU.
irq IRQ capability to bind the IRQ to.
Returns
Syscall return tag
Note
the icu argument is the implicit this pointer.
Definition at line 166 of file irq.
References L4::Cap_base::cap(), and L4::Kobject::cap().
Referenced by L4Re::Util::Event_t< PAYLOAD >::init().
l4_msgtag_t L4::Icu::unbind (unsigned irqnum, L4::Cap< Irq > irq, l4_utcb_t * utcb = l4_utcb()) throw () inline
Remove binding of an interrupt vector from the interrupt controller object.
Parameters
icu ICU to use.
irqnum IRQ vector at the ICU.
irq IRQ object to remove from the ICU.
Returns
Syscall return tag
Note
the icu argument is the implicit this pointer.
Definition at line 174 of file irq.
References L4::Cap_base::cap(), and L4::Kobject::cap().
l4_msgtag_t L4::Icu::info (l4_icu_info_t * info, l4_utcb_t * utcb = l4_utcb()) throw () inline
Get info about capabilites of ICU.
Parameters
icu ICU to use.
info Pointer to an info structure to be filled with information.
Returns
Syscall return tag
Note
the icu argument is the implicit this pointer.
Definition at line 182 of file irq.
References L4::Kobject::cap().
l4_msgtag_t L4::Icu::msi_info (unsigned irqnum, l4_umword_t * msg, l4_utcb_t * utcb = l4_utcb()) throw () inline
Get MSI info about IRQ.
Parameters
icu ICU to use.
irqnum IRQ vector at the ICU.
msg Pointer to a word to receive the message that must be used for the PCI devices MSI message.
Returns
Syscall return tag
Note
the icu argument is the implicit this pointer.
Definition at line 189 of file irq.
References L4::Kobject::cap().
l4_msgtag_t L4::Icu::mask (unsigned irqnum, l4_umword_t * label = 0, l4_timeout_t to = L4_IPC_NEVER, l4_utcb_t * utcb = l4_utcb()) throw () inline
Mask an IRQ vector.
Parameters
icu ICU to use.
irqnum IRQ vector at the ICU.
label If non-NULL the function also waits for the next message.
to Timeout for message to ICU, if unsure use L4_IPC_NEVER.
Returns
Syscall return tag
Note
the icu argument is the implicit this pointer.
Definition at line 204 of file irq.
References L4::Kobject::cap().
l4_msgtag_t L4::Icu::unmask (unsigned irqnum, l4_umword_t * label = 0, l4_timeout_t to = L4_IPC_NEVER, l4_utcb_t * utcb = l4_utcb()) throw () inline
Unmask an IRQ vector.
Parameters
icu ICU to use.
irqnum IRQ vector at the ICU.
label If non-NULL the function also waits for the next message.
to Timeout for message to ICU, if unsure use L4_IPC_NEVER.
Returns
Syscall return tag
Note
the icu argument is the implicit this pointer.
Definition at line 214 of file irq.
References L4::Kobject::cap().
l4_msgtag_t L4::Icu::set_mode (unsigned irqnum, l4_umword_t mode, l4_utcb_t * utcb = l4_utcb()) throw () inline
Set mode of interrupt.
Parameters
icu ICU to use.
irqnum IRQ vector at the ICU.
mode Mode, see L4_irq_mode.
Returns
Syscall return tag
Note
the icu argument is the implicit this pointer.
Definition at line 224 of file irq.
References L4::Kobject::cap().
The documentation for this class was generated from the following file:
l4/sys/irq