L4Re - L4 Runtime Environment: L4Re::Mem_alloc Class Reference
L4Re::Mem_alloc Class Reference
Memory allocator API
Memory allocator.
Public Types
enum Mem_alloc_flags { Continuous = 0x01, Pinned = 0x02, Super_pages = 0x04 }
Flags for the allocator.
Public Member Functions
long alloc (unsigned long size, L4::Cap< Dataspace > mem, unsigned long flags=0, unsigned long align=0) const throw ()
Allocate anonymous memory.
long free (L4::Cap< Dataspace > mem) const throw ()
Free data space.
Public Member Functions inherited from L4::Kobject
l4_msgtag_t dec_refcnt (l4_mword_t diff, l4_utcb_t *utcb=l4_utcb())
Decrement the in kernel reference counter for the object.
Additional Inherited Members
Protected Member Functions inherited from L4::Kobject
l4_cap_idx_t cap () const throw ()
Return capability selector.
Detailed Description
Memory allocator.
Memory-allocator interface, for more information see Memory-allocator API .
Definition at line 69 of file mem_alloc.
Member Enumeration Documentation
enum L4Re::Mem_alloc::Mem_alloc_flags
Flags for the allocator.
Enumerator
Continuous
Allocate physically contiguous data space, if supported by the allocator.
Pinned
Allocate pinned data space, if supported by the allocator.
Super_pages
Allocate super pages, if supported by the allocator.
Definition at line 78 of file mem_alloc.
Member Function Documentation
long L4Re::Mem_alloc::alloc (unsigned long size, L4::Cap< Dataspace > mem, unsigned long flags = 0, unsigned long align = 0) const throw ()
Allocate anonymous memory.
Parameters
size Size to be requested in bytes (granularity is (super)pages and the size is rounded up to this granularity).
mem Object capability for the data space to be allocated.
flags Flags, see Mem_alloc_flags, default none
align Log2 alignment of dataspace if supported by allocator, will be at least L4_PAGESHIFT, with Super_pages flag set at least L4_SUPERPAGESHIFT, default 0
Returns
0 on success, <0 on error
-L4_ENOMEM
IPC errors
Definition at line 38 of file mem_alloc_impl.h.
References L4::Factory::create(), and l4_error().
long L4Re::Mem_alloc::free (L4::Cap< Dataspace > mem) const throw ()
Free data space.
Parameters
mem Data space that contains the memory.
Returns
0 on success, <0 on error
-L4_EINVAL
IPC errors
Definition at line 50 of file mem_alloc_impl.h.
References L4::Ipc::Iostream::call(), l4_error(), l4_utcb(), and L4Re::Protocol::Mem_alloc.
The documentation for this class was generated from the following files:
l4/re/mem_alloc
l4/re/impl/mem_alloc_impl.h