L4Re - L4 Runtime Environment: cxx::Avl_set< Item, Compare, Alloc > Class Template Reference
cxx::Avl_set< Item, Compare, Alloc > Class Template Reference
Small C++ Template Library
AVL Tree for simple comapreable items.
Data Structures
class Node
A smart pointer to a tree item.
Public Types
typedef Item Item_type
Type for the items contained in the tree.
typedef Compare Item_compare
Type for the comparison functor.
typedef Alloc< _Node > Node_allocator
Type for the node allocator.
typedef __Avl_set_iter< _Node,
Item_type, Fwd > Iterator
Forward iterator for the set.
typedef __Avl_set_iter< _Node,
Const_item_type, Fwd > Const_iterator
Constant forward iterator for the set.
typedef __Avl_set_iter< _Node,
Item_type, Rev > Rev_iterator
Backward iterator for the set.
typedef __Avl_set_iter< _Node,
Const_item_type, Rev > Const_rev_iterator
Constant backward iterator for the set.
Public Member Functions
Avl_set (Node_allocator const &alloc=Node_allocator())
Create a AVL-tree based set.
Avl_set (Avl_set const &o)
Create a copy of an AVL-tree based set.
cxx::Pair< Iterator, int > insert (Item_type const &item)
Insert an item into the set.
int remove (Item_type const &item)
Remove an item from the set.
Node find_node (Item_type const &item) const
Lookup a node equal to item.
Node lower_bound_node (Item_type const &key) const
Find the first node greater or equal to key.
Const_iterator begin () const
Get the constant forward iterator for the first element in the set.
Const_iterator end () const
Get the end marker for the constant forward iterator.
Iterator begin ()
Get the mutable forward iterator for the first element of the set.
Iterator end ()
Get the end marker for the mutable forward iterator.
Const_rev_iterator rbegin () const
Get the constant backward iterator for the last element in the set.
Const_rev_iterator rend () const
Get the end marker for the constant backward iterator.
Rev_iterator rbegin ()
Get the mutable backward iterator for the last element of the set.
Rev_iterator rend ()
Get the end marker for the mutable backward iterator.
Detailed Description
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator>
class cxx::Avl_set< Item, Compare, Alloc >
AVL Tree for simple comapreable items.
The AVL tree can store any kind of items where a partial order is defined. The default relation is defined by the '<' operator.
Parameters
Item The type of the items to be stored in the tree.
Compare The relation to define the partial order, default is to use operator '<'.
Alloc The allocator to use for the nodes of the AVL tree.
Definition at line 106 of file avl_set.
Constructor & Destructor Documentation
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator> cxx::Avl_set< Item, Compare, Alloc >::Avl_set (Node_allocator const & alloc = Node_allocator()) inline explicit
Create a AVL-tree based set.
Parameters
comp Comparison functor.
alloc Node allocator.
Create an empty set (AVL-tree based).
Definition at line 215 of file avl_set.
template<typename Item , class Compare , template< typename A > class Alloc> cxx::Avl_set< Item, Compare, Alloc >::Avl_set (Avl_set< Item, Compare, Alloc > const & o) inline
Create a copy of an AVL-tree based set.
Parameters
o The set to copy.
Definition at line 335 of file avl_set.
References cxx::Avl_set< Item, Compare, Alloc >::begin(), cxx::Avl_set< Item, Compare, Alloc >::end(), and cxx::Avl_set< Item, Compare, Alloc >::insert().
Member Function Documentation
template<typename Item , class Compare , template< typename A > class Alloc> Pair< typename Avl_set< Item, Compare, Alloc >::Iterator, int > cxx::Avl_set< Item, Compare, Alloc >::insert (Item_type const & item)
Insert an item into the set.
Parameters
item The item to insert.
Returns
0 on success, -1 on out of memory, and -2 if the element already exists in the set.
Insert a new item into the set, each item can only be once in the set.
Definition at line 345 of file avl_set.
References cxx::Pair< First, Second >::first, and cxx::Pair< First, Second >::second.
Referenced by cxx::Avl_set< Item, Compare, Alloc >::Avl_set().
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator> int cxx::Avl_set< Item, Compare, Alloc >::remove (Item_type const & item) inline
Remove an item from the set.
Parameters
item The item to remove.
Returns
0 on success, -3 if the item does not exist, and -4 on internal error.
Definition at line 242 of file avl_set.
Referenced by cxx::Avl_map< Region, Hdlr, cxx::Lt_functor, Alloc >::remove().
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator> Node cxx::Avl_set< Item, Compare, Alloc >::find_node (Item_type const & item) const inline
Lookup a node equal to item.
Parameters
item The value to search for.
Returns
A smart pointer to the element found, if no element found the pointer is NULL.
Definition at line 267 of file avl_set.
Referenced by cxx::Avl_map< Region, Hdlr, cxx::Lt_functor, Alloc >::find_node().
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator> Node cxx::Avl_set< Item, Compare, Alloc >::lower_bound_node (Item_type const & key) const inline
Find the first node greater or equal to key.
Parameters
key the key to look for.
Returns
The first node greater or equal to key.
Definition at line 275 of file avl_set.
Referenced by cxx::Avl_map< Region, Hdlr, cxx::Lt_functor, Alloc >::lower_bound_node().
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator> Const_iterator cxx::Avl_set< Item, Compare, Alloc >::begin () const inline
Get the constant forward iterator for the first element in the set.
Returns
Constant forward iterator for the first element in the set.
Definition at line 283 of file avl_set.
Referenced by cxx::Avl_set< Item, Compare, Alloc >::Avl_set().
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator> Const_iterator cxx::Avl_set< Item, Compare, Alloc >::end () const inline
Get the end marker for the constant forward iterator.
Returns
The end marker for the constant forward iterator.
Definition at line 288 of file avl_set.
Referenced by cxx::Avl_set< Item, Compare, Alloc >::Avl_set().
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator> Iterator cxx::Avl_set< Item, Compare, Alloc >::begin () inline
Get the mutable forward iterator for the first element of the set.
Returns
The mutable forward iterator for the first element of the set.
Definition at line 294 of file avl_set.
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator> Iterator cxx::Avl_set< Item, Compare, Alloc >::end () inline
Get the end marker for the mutable forward iterator.
Returns
The end marker for mutable forward iterator.
Definition at line 299 of file avl_set.
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator> Const_rev_iterator cxx::Avl_set< Item, Compare, Alloc >::rbegin () const inline
Get the constant backward iterator for the last element in the set.
Returns
The constant backward iterator for the last element in the set.
Definition at line 305 of file avl_set.
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator> Const_rev_iterator cxx::Avl_set< Item, Compare, Alloc >::rend () const inline
Get the end marker for the constant backward iterator.
Returns
The end marker for the constant backward iterator.
Definition at line 310 of file avl_set.
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator> Rev_iterator cxx::Avl_set< Item, Compare, Alloc >::rbegin () inline
Get the mutable backward iterator for the last element of the set.
Returns
The mutable backward iterator for the last element of the set.
Definition at line 316 of file avl_set.
template<typename Item, class Compare = Lt_functor<Item>, template< typename A > class Alloc = New_allocator> Rev_iterator cxx::Avl_set< Item, Compare, Alloc >::rend () inline
Get the end marker for the mutable backward iterator.
Returns
The end marker for mutable backward iterator.
Definition at line 321 of file avl_set.
The documentation for this class was generated from the following file:
l4/cxx/avl_set