L4Re - L4 Runtime Environment: L4::Meta Class Reference
L4::Meta Class Reference
Kernel Objects
Meta interface that shall be implemented by each L4Re object and gives access to the dynamic type information for L4Re objects.
Public Member Functions
l4_msgtag_t num_interfaces (l4_utcb_t *utcb=l4_utcb()) throw ()
Get the number of interfaces implemented by this object.
l4_msgtag_t interface (int idx, l4_utcb_t *u=l4_utcb()) throw ()
Get the protocol number that must be used for the interface with the index idx.
l4_msgtag_t supports (long protocol, l4_utcb_t *u=l4_utcb()) throw ()
Figure out if the object supports the given protocol (number).
Public Member Functions inherited from L4::Kobject
l4_msgtag_t dec_refcnt (l4_mword_t diff, l4_utcb_t *utcb=l4_utcb())
Decrement the in kernel reference counter for the object.
Additional Inherited Members
Protected Member Functions inherited from L4::Kobject
l4_cap_idx_t cap () const throw ()
Return capability selector.
Detailed Description
Meta interface that shall be implemented by each L4Re object and gives access to the dynamic type information for L4Re objects.
Definition at line 41 of file meta.
Member Function Documentation
l4_msgtag_t L4::Meta::num_interfaces (l4_utcb_t * utcb = l4_utcb()) throw () inline
Get the number of interfaces implemented by this object.
Parameters
utcb is the utcb to use for sending the message.
Returns
The message tag for the operation, the label (l4_msgtag_t::label()) is set to the number of interfaces if successful, or to -error when an error occured.
Definition at line 89 of file meta.
References l4_ipc_call(), L4_IPC_NEVER, l4_msgtag(), and l4_msg_regs_t::mr.
l4_msgtag_t L4::Meta::interface (int idx, l4_utcb_t * u = l4_utcb()) throw () inline
Get the protocol number that must be used for the interface with the index idx.
Parameters
idx is the index of the interface to get the protocol number for. idx must be >= 0 and < the return value of num_interfaces().
utcb is the utcb to use for sending the message.
Returns
The message tag for the operation, the label (l4_msgtag_t::label()) is set to the protocol number of interface idx.
Definition at line 98 of file meta.
References l4_ipc_call(), L4_IPC_NEVER, l4_msgtag(), and l4_msg_regs_t::mr.
l4_msgtag_t L4::Meta::supports (long protocol, l4_utcb_t * u = l4_utcb()) throw () inline
Figure out if the object supports the given protocol (number).
Parameters
protocol is the protocol number to check for.
utcb is the utcb to use for sending the message.
Returns
The message tag for the operation, the label (l4_msgtag_t::label()) is set to 1 if protocol is supported to 0 if not.
This method is intended to be used for statically assigned protocol numbers.
Definition at line 108 of file meta.
References l4_ipc_call(), L4_IPC_NEVER, l4_msgtag(), and l4_msg_regs_t::mr.
The documentation for this class was generated from the following file:
l4/sys/meta