L4Re - L4 Runtime Environment: L4Re::Namespace Class Reference
L4Re::Namespace Class Reference
Name-space API
Name-space interface.
Public Types
enum Register_flags { Ro = L4_CAP_FPAGE_RO, Rw = L4_CAP_FPAGE_RW , Strong = L4_CAP_FPAGE_S }
Flags for registering name spaces.
Public Member Functions
long query (char const *name, L4::Cap< void > const &cap, int timeout=To_default, l4_umword_t *local_id=0, bool iterate=true) const throw ()
Query a name.
long query (char const *name, unsigned len, L4::Cap< void > const &cap, int timeout=To_default, l4_umword_t *local_id=0, bool iterate=true) const throw ()
Query a name.
long register_obj (char const *name, L4::Cap< void > const &obj, unsigned flags=Rw) const throw ()
Register an object with a name.
Public Member Functions inherited from L4::Kobject
l4_msgtag_t dec_refcnt (l4_mword_t diff, l4_utcb_t *utcb=l4_utcb())
Decrement the in kernel reference counter for the object.
Additional Inherited Members
Protected Member Functions inherited from L4::Kobject
l4_cap_idx_t cap () const throw ()
Return capability selector.
Detailed Description
Name-space interface.
All name space objects must provide this interface. However, it is not mandatory that a name space object allows to register new capabilities.
The name lookup is done iteratively, this means the hierarchical names are resolved component wise by the client itself.
Definition at line 57 of file namespace.
Member Enumeration Documentation
enum L4Re::Namespace::Register_flags
Flags for registering name spaces.
Enumerator
Ro
Read-only.
Rw
Read-write.
Strong
Strong.
Definition at line 66 of file namespace.
Member Function Documentation
long L4Re::Namespace::query (char const * name, L4::Cap< void > const & cap, int timeout = To_default, l4_umword_t * local_id = 0, bool iterate = true) const throw ()
Query a name.
Parameters
name String to query
cap Capability slot to put object into.
timeout Timeout of query in milliseconds.
Return values
local_id Local id.
Returns
<0 on failure, see l4_error_code_t.
-L4_ENOENT
IPC errors == 0 if name could be fully resolved > 0 if name could not be fully resolved
Definition at line 118 of file namespace_impl.h.
long L4Re::Namespace::query (char const * name, unsigned len, L4::Cap< void > const & cap, int timeout = To_default, l4_umword_t * local_id = 0, bool iterate = true) const throw ()
Query a name.
Parameters
name String to query
len Length of the string to query.
cap Capability slot to put object into.
timeout Timeout of query in milliseconds.
Return values
local_id Local id.
Returns
<0 on failure, see l4_error_code_t.
-L4_ENOENT
IPC errors == 0 if name could be fully resolved > 0 if name could not be fully resolved
Definition at line 84 of file namespace_impl.h.
References EXPECT_FALSE, and L4_EAGAIN.
long L4Re::Namespace::register_obj (char const * name, L4::Cap< void > const & obj, unsigned flags = Rw) const throw ()
Register an object with a name.
Parameters
name String to register.
obj Object to register.
flags Flags to use, see Register_flags, default is rw.
Returns
0 on success, <0 on failure, see l4_error_code_t.
-L4_EEXIST
-L4_EPERM
-L4_ENOMEM
-L4_EINVAL
IPC errors
Definition at line 124 of file namespace_impl.h.
References L4::Ipc::Iostream::call(), l4_error(), l4_utcb(), and L4Re::Protocol::Namespace.
The documentation for this class was generated from the following files:
l4/re/namespace
l4/re/impl/namespace_impl.h