L4Re - L4 Runtime Environment: L4::Thread Class Reference
L4::Thread Class Reference
Thread
L4 kernel thread.
Data Structures
class Attr
Thread attributes used for control_commit().
class Modify_senders
Wrapper class for modifying senders.
Public Member Functions
l4_msgtag_t ex_regs (l4_addr_t ip, l4_addr_t sp, l4_umword_t flags, l4_utcb_t *utcb=l4_utcb()) throw ()
Exchange basic thread registers.
l4_msgtag_t ex_regs (l4_addr_t *ip, l4_addr_t *sp, l4_umword_t *flags, l4_utcb_t *utcb=l4_utcb()) throw ()
Exchange basic thread registers and return previous values.
l4_msgtag_t control (Attr const &attr) throw ()
Commit the given thread-attributes object.
l4_msgtag_t switch_to (l4_utcb_t *utcb=l4_utcb()) throw ()
Switch execution to this thread.
l4_msgtag_t stats_time (l4_utcb_t *utcb=l4_utcb()) throw ()
Get consumed timed of thread in ns.
l4_msgtag_t vcpu_resume_start (l4_utcb_t *utcb=l4_utcb()) throw ()
vCPU resume, start.
l4_msgtag_t vcpu_resume_commit (l4_msgtag_t tag, l4_utcb_t *utcb=l4_utcb()) throw ()
vCPU resume, commit.
l4_msgtag_t vcpu_control (l4_addr_t vcpu_state, l4_utcb_t *utcb=l4_utcb()) throw ()
Enable or disable the vCPU feature for the thread.
l4_msgtag_t vcpu_control_ext (l4_addr_t ext_vcpu_state, l4_utcb_t *utcb=l4_utcb()) throw ()
Enable or disable the extended vCPU feature for the thread.
l4_msgtag_t register_del_irq (Cap< Irq > irq, l4_utcb_t *u=l4_utcb()) throw ()
Register an IRQ that will trigger upon deletion events.
l4_msgtag_t modify_senders (Modify_senders const &todo) throw ()
Apply sender modifiction rules.
Public Member Functions inherited from L4::Kobject
l4_msgtag_t dec_refcnt (l4_mword_t diff, l4_utcb_t *utcb=l4_utcb())
Decrement the in kernel reference counter for the object.
Additional Inherited Members
Protected Member Functions inherited from L4::Kobject
l4_cap_idx_t cap () const throw ()
Return capability selector.
Detailed Description
L4 kernel thread.
#include <l4/sys/thread>
Definition at line 38 of file thread.
Member Function Documentation
l4_msgtag_t L4::Thread::ex_regs (l4_addr_t ip, l4_addr_t sp, l4_umword_t flags, l4_utcb_t * utcb = l4_utcb()) throw () inline
Exchange basic thread registers.
Parameters
thread Thread to manipulate
ip New instruction pointer, use ~0UL to leave the instruction pointer unchanged
sp New stack pointer, use ~0UL to leave the stack pointer unchanged
flags Ex-regs flags, see L4_thread_ex_regs_flags
Returns
System call return tag
This method allows to manipulate and start a thread. The basic functionality is to set the instruction pointer and the stack pointer of a thread. Additionally, this method allows also to cancel ongoing IPC operations and to force the thread to raise an artificial exception (see flags).
Note
the thread argument is the implicit this pointer.
Definition at line 47 of file thread.
References L4::Kobject::cap().
l4_msgtag_t L4::Thread::ex_regs (l4_addr_t * ip, l4_addr_t * sp, l4_umword_t * flags, l4_utcb_t * utcb = l4_utcb()) throw () inline
Exchange basic thread registers and return previous values.
Parameters
[in] thread Thread to manipulate
[in,out] ip New instruction pointer, use ~0UL to leave the instruction pointer unchanged, return previous instruction pointer
[in,out] sp New stack pointer, use ~0UL to leave the stack pointer unchanged, returns previous stack pointer
[in,out] flags Ex-regs flags, see L4_thread_ex_regs_flags, return previous CPU flags of the thread.
Returns
System call return tag
This method allows to manipulate and start a thread. The basic functionality is to set the instruction pointer and the stack pointer of a thread. Additionally, this method allows also to cancel ongoing IPC operations and to force the thread to raise an artificial exception (see flags).
Returned values are valid only if function returns successfully.
Note
the thread argument is the implicit this pointer.
Definition at line 56 of file thread.
References L4::Kobject::cap().
l4_msgtag_t L4::Thread::control (Attr const & attr) throw () inline
Commit the given thread-attributes object.
Parameters
attr the attribute object to commit to the thread.
Definition at line 152 of file thread.
References L4::Kobject::cap().
l4_msgtag_t L4::Thread::switch_to (l4_utcb_t * utcb = l4_utcb()) throw () inline
Switch execution to this thread.
Parameters
utcb the UTCB of the current thread.
Note
The current time slice is inherited to this thread.
Definition at line 161 of file thread.
References L4::Kobject::cap().
l4_msgtag_t L4::Thread::stats_time (l4_utcb_t * utcb = l4_utcb()) throw () inline
Get consumed timed of thread in ns.
Parameters
utcb the UTCB of the current thread.
The consumed time is return as l4_kernel_clock_t at UTCB message register 0.
Definition at line 171 of file thread.
References L4::Kobject::cap().
l4_msgtag_t L4::Thread::vcpu_resume_start (l4_utcb_t * utcb = l4_utcb()) throw () inline
vCPU resume, start.
See Also
l4_thread_vcpu_resume_start
Definition at line 179 of file thread.
l4_msgtag_t L4::Thread::vcpu_resume_commit (l4_msgtag_t tag, l4_utcb_t * utcb = l4_utcb()) throw () inline
vCPU resume, commit.
See Also
l4_thread_vcpu_resume_commit
Definition at line 187 of file thread.
References L4::Kobject::cap().
l4_msgtag_t L4::Thread::vcpu_control (l4_addr_t vcpu_state, l4_utcb_t * utcb = l4_utcb()) throw () inline
Enable or disable the vCPU feature for the thread.
Parameters
thread The thread for which the vCPU feature shall be enabled or disabled.
vcpu_state The virtual address where the kernel shall store the vCPU state in case of vCPU exits. The address must be a valid kernel-user-memory address.
Returns
Systemcall result message tag.
This function enables the vCPU feature of the thread if vcpu_state is set to a valid kernel-user-memory address, or disables the vCPU feature if vcpu_state is 0.
Definition at line 194 of file thread.
References L4::Kobject::cap().
l4_msgtag_t L4::Thread::vcpu_control_ext (l4_addr_t ext_vcpu_state, l4_utcb_t * utcb = l4_utcb()) throw () inline
Enable or disable the extended vCPU feature for the thread.
Parameters
thread The thread for which the extended vCPU feature shall be enabled or disabled.
vcpu_state The virtual address where the kernel shall store the vCPU state in case of vCPU exits. The address must be a valid kernel-user-memory address.
Returns
Systemcall result message tag.
The extended vCPU feature allows the use of hardware-virtualization features such as Intel's VT or AMD's SVM.
This function enables the extended vCPU feature of the thread if vcpu_state is set to a valid kernel-user-memory address, or disables the vCPU feature if vcpu_state is 0.
Definition at line 201 of file thread.
References L4::Kobject::cap().
l4_msgtag_t L4::Thread::register_del_irq (Cap< Irq > irq, l4_utcb_t * u = l4_utcb()) throw () inline
Register an IRQ that will trigger upon deletion events.
See Also
l4_thread_register_del_irq
Definition at line 210 of file thread.
References L4::Cap_base::cap(), and L4::Kobject::cap().
l4_msgtag_t L4::Thread::modify_senders (Modify_senders const & todo) throw () inline
Apply sender modifiction rules.
Parameters
todo Prepared sender modification rules.
Returns
System call return tag.
Definition at line 270 of file thread.
References L4::Kobject::cap(), l4_ipc_call(), L4_IPC_NEVER, l4_msgtag(), and L4_PROTO_THREAD.
The documentation for this class was generated from the following file:
l4/sys/thread