L4Re - L4 Runtime Environment: L4Re::Rm Class Reference
L4Re::Rm Class Reference
Region map API
Region map.
#include <l4/re/rm>
Public Types
enum Detach_result { Detached_ds = 0, Kept_ds = 1, Split_ds = 2 , Detach_again = 4 }
Result values for detach operation.
enum Region_flags {
Read_only = 0x01, Detach_free = 0x02, Pager = 0x04, Reserved = 0x08,
Region_flags = 0x0f
}
Flags for regions.
enum Attach_flags { Search_addr = 0x20, In_area = 0x40, Eager_map = 0x80, Attach_flags = 0xf0 }
Flags for attach operation.
enum Detach_flags { Detach_exact = 1, Detach_overlap = 2, Detach_keep = 4 }
Flags for detach operation.
Public Member Functions
long reserve_area (l4_addr_t *start, unsigned long size, unsigned flags=0, unsigned char align=L4_PAGESHIFT) const throw ()
Reserve the given area in the region map.
template<typename T >
long reserve_area (T **start, unsigned long size, unsigned flags=0, unsigned char align=L4_PAGESHIFT) const throw ()
Reserve the given area in the region map.
long free_area (l4_addr_t addr) const throw ()
Free an area from the region map.
long attach (l4_addr_t *start, unsigned long size, unsigned long flags, L4::Cap< Dataspace > mem, l4_addr_t offs=0, unsigned char align=L4_PAGESHIFT) const throw ()
Attach a data space to a region.
template<typename T >
long attach (T **start, unsigned long size, unsigned long flags, L4::Cap< Dataspace > mem, l4_addr_t offs=0, unsigned char align=L4_PAGESHIFT) const throw ()
Attach a dataspace to a region.
int detach (l4_addr_t addr, L4::Cap< Dataspace > *mem, L4::Cap< L4::Task > const &task=This_task) const throw ()
Detach a region from the address space.
int detach (void *addr, L4::Cap< Dataspace > *mem, L4::Cap< L4::Task > const &task=This_task) const throw ()
Detach a region from the address space.
int detach (l4_addr_t start, unsigned long size, L4::Cap< Dataspace > *mem, L4::Cap< L4::Task > const &task) const throw ()
Detach all regions of the specified interval.
int find (l4_addr_t *addr, unsigned long *size, l4_addr_t *offset, unsigned *flags, L4::Cap< Dataspace > *m) throw ()
Find a region given an address and size.
Public Member Functions inherited from L4::Kobject
l4_msgtag_t dec_refcnt (l4_mword_t diff, l4_utcb_t *utcb=l4_utcb())
Decrement the in kernel reference counter for the object.
Additional Inherited Members
Protected Member Functions inherited from L4::Kobject
l4_cap_idx_t cap () const throw ()
Return capability selector.
Detailed Description
Region map.
Definition at line 69 of file rm.
Member Enumeration Documentation
enum L4Re::Rm::Detach_result
Result values for detach operation.
Enumerator
Detached_ds
Detached data sapce.
Kept_ds
Kept data space.
Split_ds
Splitted data space, and done.
Detach_again
Detached data space, more to do.
Definition at line 76 of file rm.
enum L4Re::Rm::Region_flags
Flags for regions.
Enumerator
Read_only
Region is read-only.
Detach_free
Free the portion of the data space after detach.
Pager
Region has a pager.
Reserved
Region is reserved (blocked)
Region_flags
Mask of all region flags.
Definition at line 87 of file rm.
enum L4Re::Rm::Attach_flags
Flags for attach operation.
Enumerator
Search_addr
Search for a suitable address range.
In_area
Search only in area, or map into area.
Eager_map
Eagerly map the attached data space in.
Attach_flags
Mask of all attach flags.
Definition at line 99 of file rm.
enum L4Re::Rm::Detach_flags
Flags for detach operation.
Enumerator
Detach_exact
Do an unmap of the exact region given.
Detach_overlap
Do an unmap of all overlapping regions.
Detach_keep
Do not free the detached data space, ignore the Detach_free.
Definition at line 109 of file rm.
Member Function Documentation
long L4Re::Rm::reserve_area (l4_addr_t * start, unsigned long size, unsigned flags = 0, unsigned char align = L4_PAGESHIFT) const throw ()
Reserve the given area in the region map.
Parameters
start The virtual start address of the area to reserve.
size The size of the area to reserve (in bytes).
flags Flags for the reserved area (see Region_flags and Attach_flags).
align Alignment of area if searched as bits (log2 value).
Return values
start Start of address.
Returns
0 on success, <0 on error
-L4_EADDRNOTAVAIL
IPC errors
This function reserves an area within the virtual address space implemented by the region map. There are two kinds of areas available:
Reserved areas (flags = Reserved), where no data spaces can be attached
Special purpose areas (flags = 0), where data spaces can be attached to the area via the In_area flag and a start address within the area itself.
Note
When searching for a free place in the virtual address space (with flags = Search_addr), the space between start and the end of the virtual address space is searched.
Definition at line 41 of file rm_impl.h.
References L4::Ipc::Iostream::call(), EXPECT_FALSE, l4_error(), l4_utcb(), and L4Re::Protocol::Rm.
template<typename T > long L4Re::Rm::reserve_area (T ** start, unsigned long size, unsigned flags = 0, unsigned char align = L4_PAGESHIFT) const throw () inline
Reserve the given area in the region map.
Parameters
start The virtual start address of the area to reserve.
size The size of the area to reserve (in bytes).
flags Flags for the reserved area (see Region_flags and Attach_flags).
align Alignment of area if searched as bits (log2 value).
Return values
start Start of address.
Returns
0 on success, <0 on error
-L4_EADDRNOTAVAIL
IPC errors
For more information, please refer to the analogous function
See Also
L4Re::Rm::reserve_area.
Definition at line 241 of file rm.
long L4Re::Rm::free_area (l4_addr_t addr) const throw ()
Free an area from the region map.
Parameters
addr An address within the area to free.
Returns
0 on success, <0 on error
-L4_ENOENT
IPC errors
Note
The data spaces that are attached to that area are not detached by this operation.
See Also
reserve_area() for more information about areas.
Definition at line 55 of file rm_impl.h.
References L4::Ipc::Iostream::call(), l4_error(), l4_utcb(), and L4Re::Protocol::Rm.
long L4Re::Rm::attach (l4_addr_t * start, unsigned long size, unsigned long flags, L4::Cap< Dataspace > mem, l4_addr_t offs = 0, unsigned char align = L4_PAGESHIFT) const throw ()
Attach a data space to a region.
Parameters
start Virtual start address
size Size of the data space to attach (in bytes)
flags Flags, see Attach_flags and Region_flags
mem Data space
offs Offset into the data space to use
align Alignment of the virtual region, log2-size, default: a page (L4_PAGESHIFT), Only meaningful if the Search_addr flag is used.
Return values
start Start of region if Search_addr was used.
Returns
0 on success, <0 on error
-L4_ENOENT
-L4_EPERM
-L4_EINVAL
-L4_EADDRNOTAVAIL
IPC errors
Makes the whole or parts of a data space visible in the virtual memory of the corresponding task. The corresponding region in the virtual address space is backed with the contents of the dataspace.
Note
When searching for a free place in the virtual address space, the space between start and the end of the virtual address space is searched.
There is no region object created, instead the region is defined by a virtual address within this range (see find).
Definition at line 63 of file rm_impl.h.
References L4::Ipc::Iostream::call(), EXPECT_FALSE, l4_error(), l4_utcb(), L4Re::Dataspace::Map_ro, L4Re::Dataspace::Map_rw, and L4Re::Protocol::Rm.
template<typename T > long L4Re::Rm::attach (T ** start, unsigned long size, unsigned long flags, L4::Cap< Dataspace > mem, l4_addr_t offs = 0, unsigned char align = L4_PAGESHIFT) const throw () inline
Attach a dataspace to a region.
See Also
attach
Definition at line 301 of file rm.
int L4Re::Rm::detach (l4_addr_t addr, L4::Cap< Dataspace > * mem, L4::Cap< L4::Task > const & task = This_task) const throw () inline
Detach a region from the address space.
Parameters
addr Virtual address of region, any address within the region is valid.
Return values
mem Dataspace that is affected. Give 0 if not interested.
Parameters
task If given, task specifies the task where the pages are unmapped. Give 0 for none. Default is current task.
Returns
Detach_result on success, <0 on error
-L4_ENOENT
IPC errors
Frees a region in the virtual address space given by addr (address type). The corresponding part of the address space is now available again.
Definition at line 451 of file rm.
int L4Re::Rm::detach (void * addr, L4::Cap< Dataspace > * mem, L4::Cap< L4::Task > const & task = This_task) const throw () inline
Detach a region from the address space.
Parameters
addr Virtual address of region, any address within the region is valid.
Return values
mem Dataspace that is affected. Give 0 if not interested.
Parameters
task If given, task specifies the task where the pages are unmapped. Give 0 for none. Default is current task.
Returns
Detach_result on success, <0 on error
-L4_ENOENT
IPC errors
Frees a region in the virtual address space given by addr (void pointer type). The corresponding part of the address space is now available again.
Definition at line 456 of file rm.
int L4Re::Rm::detach (l4_addr_t start, unsigned long size, L4::Cap< Dataspace > * mem, L4::Cap< L4::Task > const & task) const throw () inline
Detach all regions of the specified interval.
Parameters
start Start of area to detach, must be within region.
size Size of of area to detach (in bytes).
Return values
mem Dataspace that is affected. Give 0 if not interested.
Parameters
task Specifies the task where the pages are unmapped. Give 0 for none.
Returns
Detach_result on success, <0 on error
-L4_ENOENT
IPC errors
Frees all regions within the interval given by start and size. If a region overlaps the start or the end of the interval this region is only detached partly. If the interval is within one region the original region is split up into two seperate regions.
Definition at line 461 of file rm.
int L4Re::Rm::find (l4_addr_t * addr, unsigned long * size, l4_addr_t * offset, unsigned * flags, L4::Cap< Dataspace > * m) throw ()
Find a region given an address and size.
Parameters
addr Address to look for
size Size of the area to look for (in bytes).
Return values
addr Start address of the found region.
size Size of the found region (in bytes).
offset Offset at the beginning of the region within the associated dataspace.
flags Region flags, see Region_flags.
m Associated dataspace or paging service.
Returns
0 on success, <0 on error
-L4_EPERM: not allowed
-L4_ENOENT: not found
IPC errors
This function returns the properties of the region that contains the area described by the addr and size parameter.
                size-out
              /           \
             /             \
         addr-out           \
            ^________________\
------------|----------------|------------------
|           | Region         |       Dataspace |
|           |_______|___|____|                 |
------------|-------|---|-----------------------
 \         /        |\ /
  \       /         | |> size-in
  offset-out        |
                    |> addr-in
Note
The value of the size input parameter should be 1 to assure that a region can be determined unambiguously.
Definition at line 143 of file rm_impl.h.
References L4::Ipc::Iostream::call(), EXPECT_FALSE, l4_error(), l4_utcb(), and L4Re::Protocol::Rm.
The documentation for this class was generated from the following files:
l4/re/rm
l4/re/impl/rm_impl.h