L4Re - L4 Runtime Environment: L4::Vcon Class Reference
L4::Vcon Class Reference
Virtual Console
C++ L4 Vcon.
Public Member Functions
l4_msgtag_t send (char const *buf, int size, l4_utcb_t *utcb=l4_utcb()) const throw ()
Send data to virtual console.
long write (char const *buf, int size, l4_utcb_t *utcb=l4_utcb()) const throw ()
Write data to virtual console.
int read (char *buf, int size, l4_utcb_t *utcb=l4_utcb()) const throw ()
Read data from virtual console.
l4_msgtag_t set_attr (l4_vcon_attr_t const *attr, l4_utcb_t *utcb=l4_utcb()) const throw ()
Set attributes of a Vcon.
l4_msgtag_t get_attr (l4_vcon_attr_t *attr, l4_utcb_t *utcb=l4_utcb()) const throw ()
Get attributes of a Vcon.
Public Member Functions inherited from L4::Icu
l4_msgtag_t bind (unsigned irqnum, L4::Cap< Irq > irq, l4_utcb_t *utcb=l4_utcb()) throw ()
Bind an interrupt vector of an interrupt controller to an interrupt object.
l4_msgtag_t unbind (unsigned irqnum, L4::Cap< Irq > irq, l4_utcb_t *utcb=l4_utcb()) throw ()
Remove binding of an interrupt vector from the interrupt controller object.
l4_msgtag_t info (l4_icu_info_t *info, l4_utcb_t *utcb=l4_utcb()) throw ()
Get info about capabilites of ICU.
l4_msgtag_t msi_info (unsigned irqnum, l4_umword_t *msg, l4_utcb_t *utcb=l4_utcb()) throw ()
Get MSI info about IRQ.
l4_msgtag_t mask (unsigned irqnum, l4_umword_t *label=0, l4_timeout_t to=L4_IPC_NEVER, l4_utcb_t *utcb=l4_utcb()) throw ()
Mask an IRQ vector.
l4_msgtag_t unmask (unsigned irqnum, l4_umword_t *label=0, l4_timeout_t to=L4_IPC_NEVER, l4_utcb_t *utcb=l4_utcb()) throw ()
Unmask an IRQ vector.
l4_msgtag_t set_mode (unsigned irqnum, l4_umword_t mode, l4_utcb_t *utcb=l4_utcb()) throw ()
Set mode of interrupt.
Public Member Functions inherited from L4::Kobject
l4_msgtag_t dec_refcnt (l4_mword_t diff, l4_utcb_t *utcb=l4_utcb())
Decrement the in kernel reference counter for the object.
Additional Inherited Members
Protected Member Functions inherited from L4::Kobject
l4_cap_idx_t cap () const throw ()
Return capability selector.
Detailed Description
C++ L4 Vcon.
#include <l4/sys/vcon>
See Also
Virtual Console for an overview and C bindings.
Definition at line 41 of file vcon.
Member Function Documentation
l4_msgtag_t L4::Vcon::send (char const * buf, int size, l4_utcb_t * utcb = l4_utcb()) const throw () inline
Send data to virtual console.
Parameters
vcon Vcon object.
buf Pointer to data buffer.
size Size of buffer in bytes.
Returns
Syscall return tag
Note
Size must not exceed L4_VCON_WRITE_SIZE.
vcon is the implicit this pointer.
Definition at line 52 of file vcon.
References L4::Kobject::cap().
long L4::Vcon::write (char const * buf, int size, l4_utcb_t * utcb = l4_utcb()) const throw () inline
Write data to virtual console.
Parameters
vcon Vcon object.
buf Pointer to data buffer.
size Size of buffer in bytes.
Returns
Number of bytes written to the virtual console.
Note
vcon is the implicit this pointer.
Definition at line 60 of file vcon.
References L4::Kobject::cap().
int L4::Vcon::read (char * buf, int size, l4_utcb_t * utcb = l4_utcb()) const throw () inline
Read data from virtual console.
Parameters
vcon Vcon object.
buf Pointer to data buffer.
size Size of buffer in bytes.
Returns
Negative error code on error, > size if more to read, size bytes are in the buffer, <= size bytes read
Note
vcon is the implicit this pointer.
Definition at line 68 of file vcon.
References L4::Kobject::cap().
l4_msgtag_t L4::Vcon::set_attr (l4_vcon_attr_t const * attr, l4_utcb_t * utcb = l4_utcb()) const throw () inline
Set attributes of a Vcon.
Parameters
vcon Vcon object.
attr Attribute structure.
Returns
Syscall return tag
Note
vcon is the implicit this pointer.
Definition at line 76 of file vcon.
References L4::Kobject::cap().
l4_msgtag_t L4::Vcon::get_attr (l4_vcon_attr_t * attr, l4_utcb_t * utcb = l4_utcb()) const throw () inline
Get attributes of a Vcon.
Parameters
vcon Vcon object.
Return values
attr Attribute structure.
Returns
Syscall return tag
Note
vcon is the implicit this pointer.
Definition at line 84 of file vcon.
References L4::Kobject::cap().
The documentation for this class was generated from the following file:
l4/sys/vcon