L4Re - L4 Runtime Environment: L4::Scheduler Class Reference
L4::Scheduler Class Reference
Scheduler object.
Public Member Functions
l4_msgtag_t info (l4_umword_t *cpu_max, l4_sched_cpu_set_t *cpus, l4_utcb_t *utcb=l4_utcb()) const throw ()
Get scheduler information.
l4_msgtag_t run_thread (Cap< Thread > const &thread, l4_sched_param_t const &sp, l4_utcb_t *utcb=l4_utcb()) const throw ()
Run a thread on a Scheduler.
l4_msgtag_t idle_time (l4_sched_cpu_set_t const &cpus, l4_utcb_t *utcb=l4_utcb()) const throw ()
Query idle time of a CPU, in µs.
bool is_online (l4_umword_t cpu, l4_utcb_t *utcb=l4_utcb()) const throw ()
Query if a CPU is online.
Public Member Functions inherited from L4::Icu
l4_msgtag_t bind (unsigned irqnum, L4::Cap< Irq > irq, l4_utcb_t *utcb=l4_utcb()) throw ()
Bind an interrupt vector of an interrupt controller to an interrupt object.
l4_msgtag_t unbind (unsigned irqnum, L4::Cap< Irq > irq, l4_utcb_t *utcb=l4_utcb()) throw ()
Remove binding of an interrupt vector from the interrupt controller object.
l4_msgtag_t info (l4_icu_info_t *info, l4_utcb_t *utcb=l4_utcb()) throw ()
Get info about capabilites of ICU.
l4_msgtag_t msi_info (unsigned irqnum, l4_umword_t *msg, l4_utcb_t *utcb=l4_utcb()) throw ()
Get MSI info about IRQ.
l4_msgtag_t mask (unsigned irqnum, l4_umword_t *label=0, l4_timeout_t to=L4_IPC_NEVER, l4_utcb_t *utcb=l4_utcb()) throw ()
Mask an IRQ vector.
l4_msgtag_t unmask (unsigned irqnum, l4_umword_t *label=0, l4_timeout_t to=L4_IPC_NEVER, l4_utcb_t *utcb=l4_utcb()) throw ()
Unmask an IRQ vector.
l4_msgtag_t set_mode (unsigned irqnum, l4_umword_t mode, l4_utcb_t *utcb=l4_utcb()) throw ()
Set mode of interrupt.
Public Member Functions inherited from L4::Kobject
l4_msgtag_t dec_refcnt (l4_mword_t diff, l4_utcb_t *utcb=l4_utcb())
Decrement the in kernel reference counter for the object.
Additional Inherited Members
Protected Member Functions inherited from L4::Kobject
l4_cap_idx_t cap () const throw ()
Return capability selector.
Detailed Description
Scheduler object.
#include <l4/sys/scheduler>
See Also
Scheduler for an overview description.
Definition at line 41 of file scheduler.
Member Function Documentation
l4_msgtag_t L4::Scheduler::info (l4_umword_t * cpu_max, l4_sched_cpu_set_t * cpus, l4_utcb_t * utcb = l4_utcb()) const throw () inline
Get scheduler information.
Parameters
scheduler Scheduler object.
Return values
cpu_max maximum number of CPUs ever available.
Parameters
cpus cpus.offset is first CPU of interest. cpus.granularity (see l4_sched_cpu_set_t).
Return values
cpus cpus.map Bitmap of online CPUs.
Returns
0 on success, <0 error code otherwise.
Note
scheduler is the implicit this pointer.
Definition at line 50 of file scheduler.
References L4::Kobject::cap().
l4_msgtag_t L4::Scheduler::run_thread (Cap< Thread > const & thread, l4_sched_param_t const & sp, l4_utcb_t * utcb = l4_utcb()) const throw () inline
Run a thread on a Scheduler.
Parameters
scheduler Scheduler object.
thread Thread to run.
sp Scheduling parameters.
Returns
0 on success, <0 error code otherwise.
Note
scheduler is the implicit this pointer.
Definition at line 58 of file scheduler.
References L4::Cap_base::cap(), and L4::Kobject::cap().
l4_msgtag_t L4::Scheduler::idle_time (l4_sched_cpu_set_t const & cpus, l4_utcb_t * utcb = l4_utcb()) const throw () inline
Query idle time of a CPU, in µs.
Parameters
scheduler Scheduler object.
cpus Set of CPUs to query.
The consumed time is returned as l4_kernel_clock_t at UTCB message register 0.
Note
scheduler is the implicit this pointer.
Definition at line 67 of file scheduler.
References L4::Kobject::cap().
bool L4::Scheduler::is_online (l4_umword_t cpu, l4_utcb_t * utcb = l4_utcb()) const throw () inline
Query if a CPU is online.
Parameters
scheduler Scheduler object.
cpu CPU number.
Returns
true if online, false if not (or any other query error).
Note
scheduler is the implicit this pointer.
Definition at line 76 of file scheduler.
References L4::Kobject::cap().
The documentation for this class was generated from the following file:
l4/sys/scheduler