L4Re - L4 Runtime Environment: Capabilities
Capabilities
Base API
Functions and definitions related to capabilities.
Data Structures
class L4::Cap_base
Base class for all kinds of capabilities.
class L4::Cap< T >
Capability Selector a la C++.
Macros
#define L4_DISABLE_COPY(_class)
Disable copy of a class.
#define L4_KOBJECT_DISABLE_COPY(_class)
Disable copy and instantiation of a class.
#define L4_KOBJECT(_class) L4_KOBJECT_DISABLE_COPY(_class)
Declare a kernel object class.
Typedefs
typedef unsigned long l4_cap_idx_t
L4 Capability selector Type.
Enumerations
enum l4_cap_consts_t { L4_CAP_SHIFT, L4_CAP_SIZE , L4_CAP_MASK, L4_INVALID_CAP }
Constants related to capability selectors.
enum l4_default_caps_t {
L4_BASE_TASK_CAP, L4_BASE_FACTORY_CAP, L4_BASE_THREAD_CAP, L4_BASE_PAGER_CAP,
L4_BASE_LOG_CAP, L4_BASE_ICU_CAP, L4_BASE_SCHEDULER_CAP
}
Default capabilities setup for the initial tasks.
Functions
template<typename T , typename F >
Cap< T > L4::cap_cast (Cap< F > const &c) throw ()
static_cast for capabilities.
template<typename T , typename F >
Cap< T > L4::cap_reinterpret_cast (Cap< F > const &c) throw ()
reinterpret_cast for capabilities.
template<typename T , typename F >
Cap< T > L4::cap_dynamic_cast (Cap< F > const &c) throw ()
dynamic_cast for capabilities.
unsigned l4_is_invalid_cap (l4_cap_idx_t c) L4_NOTHROW
Test if a capability selector is the invalid capability.
unsigned l4_is_valid_cap (l4_cap_idx_t c) L4_NOTHROW
Test if a capability selector is a valid selector.
unsigned l4_capability_equal (l4_cap_idx_t c1, l4_cap_idx_t c2) L4_NOTHROW
Test if two capability selectors are equal.
Detailed Description
Functions and definitions related to capabilities.
#include <l4/sys/consts.h>
C++ interface for capabilities:
#include <l4/sys/capability>
C interface for capabilities:
#include <l4/sys/types.h>
Macro Definition Documentation
#define L4_DISABLE_COPY (_class)
Value:
private:                              \
    _class(_class const &);             \
    _class operator = (_class const &);
Disable copy of a class.
Parameters
_class is the name of the class that shall not have value copy semantics.
The typical use of this is:
* class Non_value
* {
*   L4_DISABLE_COPY(Non_value)
*
*   ...
* }
*
Definition at line 397 of file capability.
#define L4_KOBJECT_DISABLE_COPY (_class)
Value:
protected:                            \
    _class();                           \
  L4_DISABLE_COPY(_class)
Disable copy and instantiation of a class.
Parameters
_class is the name of the class to be not copyable and not instantiatable.
The typical use looks like:
* class Type
* {
*   L4_KOBJECT_DISABLE_COPY(Type)
* };
*
Definition at line 417 of file capability.
#define L4_KOBJECT (_class) L4_KOBJECT_DISABLE_COPY(_class)
Declare a kernel object class.
Parameters
_class is the class name.
The use of this macro disables copy and instantiation of the class as needed for kernel object classes derived from L4::Kobject.
The typical use looks like:
* class Type : public L4::Kobject_t<Type, L4::Kobject>
* {
*   L4_KOBJECT(Type)
* };
*
Definition at line 440 of file capability.
Typedef Documentation
typedef unsigned long l4_cap_idx_t
L4 Capability selector Type.
#include <l4/sys/types.h>
Definition at line 319 of file types.h.
Enumeration Type Documentation
enum l4_cap_consts_t
Constants related to capability selectors.
Enumerator
L4_CAP_SHIFT
Capability index shift.
L4_CAP_SIZE
Offset of two consecutive capability selectors.
L4_CAP_MASK
Mask to get only the relevant bits of an l4_cap_idx_t.
L4_INVALID_CAP
Invalid capability selector.
Definition at line 134 of file consts.h.
enum l4_default_caps_t
Default capabilities setup for the initial tasks.
#include <l4/sys/consts.h>
These capability selectors are setup per default by the micro kernel for the two initial tasks, the Root-Pager (Sigma0) and the Root-Task (Moe).
Attention
This constants do not have any particular meaning for applications started by Moe, see Initial Environment for this kind of information.
See Also
Initial Environment for information useful for normal user applications.
Enumerator
L4_BASE_TASK_CAP
Capability selector for the current task.
L4_BASE_FACTORY_CAP
Capability selector for the factory.
L4_BASE_THREAD_CAP
Capability selector for the first thread.
L4_BASE_PAGER_CAP
Capability selector for the pager gate.
L4_BASE_LOG_CAP
Capability selector for the log object.
L4_BASE_ICU_CAP
Capability selector for the base icu object.
L4_BASE_SCHEDULER_CAP
Capability selector for the scheduler cap.
Definition at line 248 of file consts.h.
Function Documentation
template<typename T , typename F > Cap<T> L4::cap_cast (Cap< F > const & c) throw () inline
static_cast for capabilities.
Parameters
T is the target type of the capability
F is the source type (and is usually implicitly set)
c is the source capability that shall be casted
Returns
A capability typed to the interface T.
The use of this cast operator is similar to the static_cast<>() for C++ pointers. It does the same type checking and adjustment like C++ does on pointers.
Example code:
* L4::Cap<L4::Kobject> obj = ... ;
* L4::Cap<L4::Icu> icu = L4::cap_cast<L4::Icu>(obj);
*
Definition at line 343 of file capability.
Referenced by L4Re::Cap_alloc::alloc().
template<typename T , typename F > Cap<T> L4::cap_reinterpret_cast (Cap< F > const & c) throw () inline
reinterpret_cast for capabilities.
Parameters
T is the target type of the capability
F is the source type (and is usually implicitly set)
c is the source capability that shall be casted
Returns
A capability typed to the interface T.
The use of this cast operator is similar to the reinterpret_cast<>() for C++ pointers. It does not do any type checking or type adjustment.
Example code:
* L4::Cap<L4::Kobject> obj = ... ;
* L4::Cap<L4::Icu> icu = L4::cap_reinterpret_cast<L4::Icu>(obj);
*
Definition at line 367 of file capability.
Referenced by L4::cap_dynamic_cast().
template<typename T , typename F > Cap<T> L4::cap_dynamic_cast (Cap< F > const & c) throw () inline
dynamic_cast for capabilities.
Parameters
T is the target type of the capability
F is the source type (and is usually implicitly set)
c is the source capability that shall be casted
Returns
A capability typed to the interface T. If the object does not support the target interface T or does not support the L4::Meta interface the result is the invalid capability selector.
The use of this cast operator is similar to the dynamic_cast<>() for C++ pointers. It also induces overhead, because it uses the meta interface (L4::Meta) to do runtime type checking.
Example code:
* L4::Cap<L4::Kobject> obj = ... ;
* L4::Cap<L4::Icu> icu = L4::cap_dynamic_cast<L4::Icu>(obj);
*
Definition at line 550 of file capability.
References L4::cap_reinterpret_cast(), and l4_error().
unsigned l4_is_invalid_cap (l4_cap_idx_t c) inline
Test if a capability selector is the invalid capability.
Parameters
c Capability selector
Returns
Boolean value
Examples:
examples/libs/l4re/c/ma+rm.c, examples/sys/aliens/main.c, examples/sys/isr/main.c, examples/sys/singlestep/main.c, examples/sys/start-with-exc/main.c, and examples/sys/utcb-ipc/main.c.
Definition at line 350 of file types.h.
unsigned l4_is_valid_cap (l4_cap_idx_t c) inline
Test if a capability selector is a valid selector.
Parameters
c Capability selector
Returns
Boolean value
Definition at line 354 of file types.h.
unsigned l4_capability_equal (l4_cap_idx_t c1, l4_cap_idx_t c2) inline
Test if two capability selectors are equal.
Parameters
c1 Capability
c2 Capability
Returns
1 if equal, 0 if not equal
Definition at line 358 of file types.h.
References L4_CAP_SHIFT.